const paths = {
    ROOT: '/',
    CART: '/cart',
    LOGIN: '/login',
    ABOUT: '/about-us',
    CONTACT: '/contact',
    MEETTHESTAFF: '/staff',
    REGISTER: '/register',
    CUSTOMBUILDS: '/custom-builds',
    PRODUCTDETAIL: '/product-details',
    PRODUCTDETAILID: '/product-details/:id',
    PRODUCTLISTCATEGORY: '/product-list/category/:categoryName',
    PRODUCTLISTCATEGORYPAGE: '/product-list/category/:categoryName/:pageNumParam',
    PRODUCTLISTSEARCH: '/product-list/search/:searchQuery',
    PRODUCTLISTSEARCHPAGE: '/product-list/search/:searchQuery/:pageNumParam',
    PRODUCTLISTCATEGORYSEARCH: '/product-list/category/:categoryName/search/:searchQuery',
    PRODUCTLISTCATEGORYSEARCHPAGE: '/product-list/category/:categoryName/search/:searchQuery/:pageNumParam',
    PRODUCTLISTPAGENUM: '/product-list/:pageNumParam',
    PRODUCTLIST: '/product-list',
    USERCARTDETAIL: '/user/cart-details',
    USERORDERDETAIL: '/user/order-details',
    USERORDERDETAILID: '/user/order-details/:id',
    USERORDER: '/user/my-orders',
    USERPROFILE: '/user',
    ADMINUSERS: '/admin/users',
    ADMINPRODUCTS: '/admin/products',
    ADMINEDITPRODUCT: '/admin/edit-product/:id',
    ADMINORDERS: '/admin/orders',
    ADMINORDERDETAILS: '/admin/order-details/:id',
    ADMINEDITUSER: '/admin/edit-user/:id',
    ADMINCREATEPRODUCT: '/admin/create-new-product',
    ADMINCHATS: '/admin/chats',
    ADMINMESSAGE: '/admin/messages',
    ADMINANALYTICS: '/admin/analytics',
    ADMINSETTINGS: '/admin/settings/:id',
    NOTFOUND: '*',

};

export default paths;